version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=production
      - JWT_SECRET=prod_secret_vk_traders_2026
    volumes:
      - ../database:/app/database
    restart: unless-stopped
